# Generated by Django 3.1.5 on 2021-05-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_member_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
