# Generated by Django 3.1.5 on 2021-05-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_auto_20210526_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
