# Generated by Django 3.1.5 on 2021-05-26 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_auto_20210526_2155'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rank',
        ),
    ]
